// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: guestbook/v1/guestbook.proto

package guestbookv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Nick          *string                `protobuf:"bytes,2,opt,name=nick,proto3,oneof" json:"nick,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_guestbook_v1_guestbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guestbook_v1_guestbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_guestbook_v1_guestbook_proto_rawDescGZIP(), []int{0}
}

func (x *PostMessageRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PostMessageRequest) GetNick() string {
	if x != nil && x.Nick != nil {
		return *x.Nick
	}
	return ""
}

func (x *PostMessageRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *PostMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PostMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageResponse) Reset() {
	*x = PostMessageResponse{}
	mi := &file_guestbook_v1_guestbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageResponse) ProtoMessage() {}

func (x *PostMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guestbook_v1_guestbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageResponse.ProtoReflect.Descriptor instead.
func (*PostMessageResponse) Descriptor() ([]byte, []int) {
	return file_guestbook_v1_guestbook_proto_rawDescGZIP(), []int{1}
}

func (x *PostMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_guestbook_v1_guestbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guestbook_v1_guestbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_guestbook_v1_guestbook_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageEntry        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_guestbook_v1_guestbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guestbook_v1_guestbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_guestbook_v1_guestbook_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessagesResponse) GetMessages() []*MessageEntry {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MessageEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Nick          string                 `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEntry) Reset() {
	*x = MessageEntry{}
	mi := &file_guestbook_v1_guestbook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEntry) ProtoMessage() {}

func (x *MessageEntry) ProtoReflect() protoreflect.Message {
	mi := &file_guestbook_v1_guestbook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEntry.ProtoReflect.Descriptor instead.
func (*MessageEntry) Descriptor() ([]byte, []int) {
	return file_guestbook_v1_guestbook_proto_rawDescGZIP(), []int{4}
}

func (x *MessageEntry) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MessageEntry) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *MessageEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageEntry) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

var File_guestbook_v1_guestbook_proto protoreflect.FileDescriptor

const file_guestbook_v1_guestbook_proto_rawDesc = "" +
	"\n" +
	"\x1cguestbook/v1/guestbook.proto\x12\fguestbook.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x01\n" +
	"\x12PostMessageRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04nick\x18\x02 \x01(\tH\x01R\x04nick\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x02R\x05email\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessageB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_nickB\b\n" +
	"\x06_email\"/\n" +
	"\x13PostMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x12GetMessagesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"M\n" +
	"\x13GetMessagesResponse\x126\n" +
	"\bmessages\x18\x01 \x03(\v2\x1a.guestbook.v1.MessageEntryR\bmessages\"\x8a\x01\n" +
	"\fMessageEntry\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x12\n" +
	"\x04nick\x18\x02 \x01(\tR\x04nick\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12*\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02tsB\a\n" +
	"\x05_name2\xba\x01\n" +
	"\x10GuestbookService\x12R\n" +
	"\vPostMessage\x12 .guestbook.v1.PostMessageRequest\x1a!.guestbook.v1.PostMessageResponse\x12R\n" +
	"\vGetMessages\x12 .guestbook.v1.GetMessagesRequest\x1a!.guestbook.v1.GetMessagesResponseB'Z%internal/rpc/guestbook/v1;guestbookv1b\x06proto3"

var (
	file_guestbook_v1_guestbook_proto_rawDescOnce sync.Once
	file_guestbook_v1_guestbook_proto_rawDescData []byte
)

func file_guestbook_v1_guestbook_proto_rawDescGZIP() []byte {
	file_guestbook_v1_guestbook_proto_rawDescOnce.Do(func() {
		file_guestbook_v1_guestbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guestbook_v1_guestbook_proto_rawDesc), len(file_guestbook_v1_guestbook_proto_rawDesc)))
	})
	return file_guestbook_v1_guestbook_proto_rawDescData
}

var file_guestbook_v1_guestbook_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_guestbook_v1_guestbook_proto_goTypes = []any{
	(*PostMessageRequest)(nil),    // 0: guestbook.v1.PostMessageRequest
	(*PostMessageResponse)(nil),   // 1: guestbook.v1.PostMessageResponse
	(*GetMessagesRequest)(nil),    // 2: guestbook.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil),   // 3: guestbook.v1.GetMessagesResponse
	(*MessageEntry)(nil),          // 4: guestbook.v1.MessageEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_guestbook_v1_guestbook_proto_depIdxs = []int32{
	4, // 0: guestbook.v1.GetMessagesResponse.messages:type_name -> guestbook.v1.MessageEntry
	5, // 1: guestbook.v1.MessageEntry.ts:type_name -> google.protobuf.Timestamp
	0, // 2: guestbook.v1.GuestbookService.PostMessage:input_type -> guestbook.v1.PostMessageRequest
	2, // 3: guestbook.v1.GuestbookService.GetMessages:input_type -> guestbook.v1.GetMessagesRequest
	1, // 4: guestbook.v1.GuestbookService.PostMessage:output_type -> guestbook.v1.PostMessageResponse
	3, // 5: guestbook.v1.GuestbookService.GetMessages:output_type -> guestbook.v1.GetMessagesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_guestbook_v1_guestbook_proto_init() }
func file_guestbook_v1_guestbook_proto_init() {
	if File_guestbook_v1_guestbook_proto != nil {
		return
	}
	file_guestbook_v1_guestbook_proto_msgTypes[0].OneofWrappers = []any{}
	file_guestbook_v1_guestbook_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guestbook_v1_guestbook_proto_rawDesc), len(file_guestbook_v1_guestbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guestbook_v1_guestbook_proto_goTypes,
		DependencyIndexes: file_guestbook_v1_guestbook_proto_depIdxs,
		MessageInfos:      file_guestbook_v1_guestbook_proto_msgTypes,
	}.Build()
	File_guestbook_v1_guestbook_proto = out.File
	file_guestbook_v1_guestbook_proto_goTypes = nil
	file_guestbook_v1_guestbook_proto_depIdxs = nil
}
