apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kolchurin-dev
  namespace: kolchurin-dev
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - kolchurin.dev
        - www.kolchurin.dev
      secretName: kolchurin-dev-tls
  rules:
    - host: kolchurin.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kolchurin-dev-grpc
  namespace: kolchurin-dev
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: grpc
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - api.kolchurin.dev
      secretName: kolchurin-dev-grpc-tls
  rules:
    - host: api.kolchurin.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
